[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "#4b85a8"
playing = "#4b85a8"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "#d98100"
error_bg = "black"
statusbar = "black"
statusbar_progress = "#4b85a8"
statusbar_bg = "#4b85a8"
cmdline = "light white"
cmdline_bg = "black"
